# Generated by Django 5.0 on 2023-12-20 05:43

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.IntegerField()),
                ('department_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_code', models.IntegerField()),
                ('desigantion_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.IntegerField()),
                ('district_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GradePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradepay', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hpc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpc_code', models.IntegerField()),
                ('hpc_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PayBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payband_code', models.IntegerField()),
                ('payband', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lac_name', models.CharField(max_length=50)),
                ('hpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.hpc')),
            ],
            options={
                'unique_together': {('hpc', 'lac_name')},
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('emp_grade', models.CharField(max_length=8)),
                ('emp_type', models.CharField(max_length=25)),
                ('bank_name', models.CharField(max_length=120)),
                ('bank_branch', models.CharField(max_length=120)),
                ('bank_ifsc', models.CharField(max_length=15)),
                ('bank_ac', models.IntegerField()),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.designation')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.district')),
                ('gradepay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.gradepay')),
                ('lac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lac')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.office')),
            ],
        ),
        migrations.AddField(
            model_name='gradepay',
            name='payband',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.payband'),
        ),
        migrations.AlterUniqueTogether(
            name='gradepay',
            unique_together={('payband', 'gradepay')},
        ),
    ]
